# GoReleaser configuration for CCLogAnalysis
# Documentation: https://goreleaser.com

version: 2

project_name: ccloganalysis

before:
  hooks:
    # Build React frontend before building Go backend
    - sh -c "cd web && npm ci && npm run build"
    - sh -c "rm -rf internal/static/dist"
    - sh -c "cp -r web/dist internal/static/"

builds:
  - id: ccloganalysis
    main: ./cmd/server
    binary: ccloganalysis

    # Disable CGO for pure Go build (modernc.org/sqlite)
    env:
      - CGO_ENABLED=0

    # Build targets
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    # Exclude Windows ARM64 (not commonly used)
    ignore:
      - goos: windows
        goarch: arm64

    # ldflags for optimization and version information
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    # Archive naming: ccloganalysis_<version>_<os>_<arch>
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

    # Format by OS (tar.gz for Unix-like, zip for Windows)
    format_overrides:
      - goos: windows
        format: zip

    # Include README and LICENSE
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: a-tak
    name: CCLogAnalysis

  # Release notes template
  name_template: "{{.ProjectName}} v{{.Version}}"

  # Draft release for manual review before publishing
  draft: false

  # Prerelease detection
  prerelease: auto
